version: 2
jobs:
  build:
    branches:
      only:
        - master
        - /feature.*/
        - /bugfix.*/

    docker:
      - image: cimg/openjdk:17.0

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "versions.properties" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: ./gradlew dependencies -PGCP_PROJECT_ID=dummy_project_id

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "versions.properties" }}

      - run: ./gradlew test -PGCP_PROJECT_ID=dummy_project_id
      - store_artifacts:
          path: build/reports/tests
          destination: reports

      - run: ./gradlew build -PGCP_PROJECT_ID=dummy_project_id

      - store_artifacts:
          path: build/libs
          destination: artifacts

      - store_test_results:
          path: build/test-results

